// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Loginpayload struct {
	Token   *string `json:"token,omitempty"`
	Message string  `json:"message"`
	Success bool    `json:"success"`
}

type Mutation struct {
}

type NewUser struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Query struct {
}

type UpdateUser struct {
	ID    string  `json:"id"`
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}
